//
//  MCPProviderHealthSnapshotStore.swift
//  osaurus
//
//  Persisted MCP provider health snapshots generated by explicit user probes.
//

import Foundation

extension Foundation.Notification.Name {
    static let mcpProviderHealthSnapshotChanged = Foundation.Notification.Name(
        "MCPProviderHealthSnapshotChanged"
    )
}

public struct MCPProviderHealthSnapshot: Codable, Identifiable, Sendable, Equatable {
    public var id: UUID { providerId }
    public let providerId: UUID
    public let providerName: String
    public let transportSummary: String
    public let lastProbe: MCPProviderProbeResult
    public let updatedAt: Date

    public init(
        providerId: UUID,
        providerName: String,
        transportSummary: String,
        lastProbe: MCPProviderProbeResult,
        updatedAt: Date = Date()
    ) {
        self.providerId = providerId
        self.providerName = providerName
        self.transportSummary = transportSummary
        self.lastProbe = lastProbe
        self.updatedAt = updatedAt
    }
}

public enum MCPProviderHealthSnapshotStore {
    nonisolated(unsafe) public static var overrideURL: URL?
    private static let lock = NSLock()

    private struct Envelope: Codable, Sendable, Equatable {
        var snapshots: [MCPProviderHealthSnapshot]
    }

    public static func load() -> [UUID: MCPProviderHealthSnapshot] {
        withLock {
            loadUnlocked()
        }
    }

    private static func loadUnlocked() -> [UUID: MCPProviderHealthSnapshot] {
        let url = fileURL()
        guard let data = try? Data(contentsOf: url) else { return [:] }
        guard let envelope = try? JSONDecoder().decode(Envelope.self, from: data) else { return [:] }
        return envelope.snapshots.reduce(into: [:]) { snapshots, snapshot in
            if let existing = snapshots[snapshot.providerId], existing.updatedAt > snapshot.updatedAt {
                return
            }
            snapshots[snapshot.providerId] = snapshot
        }
    }

    public static func snapshot(providerId: UUID) -> MCPProviderHealthSnapshot? {
        load()[providerId]
    }

    public static func record(_ result: MCPProviderProbeResult, for provider: MCPProvider) {
        withLock {
            var snapshots = loadUnlocked()
            snapshots[provider.id] = MCPProviderHealthSnapshot(
                providerId: provider.id,
                providerName: provider.name,
                transportSummary: result.transportSummary,
                lastProbe: result
            )
            saveUnlocked(snapshots)
        }
        notify(providerId: provider.id)
    }

    public static func clear(providerId: UUID) {
        withLock {
            var snapshots = loadUnlocked()
            snapshots.removeValue(forKey: providerId)
            saveUnlocked(snapshots)
        }
        notify(providerId: providerId)
    }

    public static func save(_ snapshots: [UUID: MCPProviderHealthSnapshot]) {
        withLock {
            saveUnlocked(snapshots)
        }
    }

    private static func saveUnlocked(_ snapshots: [UUID: MCPProviderHealthSnapshot]) {
        let url = fileURL()
        OsaurusPaths.ensureExistsSilent(url.deletingLastPathComponent())
        let ordered = snapshots.values.sorted {
            if $0.providerName == $1.providerName {
                return $0.providerId.uuidString < $1.providerId.uuidString
            }
            return $0.providerName.localizedStandardCompare($1.providerName) == .orderedAscending
        }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        do {
            let data = try encoder.encode(Envelope(snapshots: ordered))
            try data.write(to: url, options: [.atomic])
        } catch {
            print("[Osaurus] Failed to save MCP health snapshots: \(error)")
        }
    }

    private static func withLock<T>(_ operation: () -> T) -> T {
        lock.lock()
        defer { lock.unlock() }
        return operation()
    }

    private static func fileURL() -> URL {
        if let overrideURL { return overrideURL }
        return OsaurusPaths.providers().appendingPathComponent("mcp-health.json")
    }

    private static func notify(providerId: UUID) {
        NotificationCenter.default.post(
            name: Foundation.Notification.Name.mcpProviderHealthSnapshotChanged,
            object: providerId
        )
    }
}
