//
//  ChatTurnData.swift
//  osaurus
//
//  Codable representation of ChatTurn for persistence
//

import Foundation

/// Codable version of ChatTurn for session persistence
public struct ChatTurnData: Codable, Identifiable, Sendable {
    public let id: UUID
    public let role: MessageRole
    public var content: String
    public var attachments: [Attachment]
    public var toolCalls: [ToolCall]?
    public var toolCallId: String?
    public var toolResults: [String: String]
    /// Wall-clock duration (seconds) each tool call took, keyed by call id.
    /// Drives the "· 1.2s" elapsed label; empty for legacy turns.
    public var toolCallDurations: [String: TimeInterval]
    /// Seconds the model spent thinking; drives "Thought for 30s". Nil when unknown.
    public var thinkingDuration: TimeInterval?
    public var thinking: String
    /// Wall-clock when the turn was created. Nil for legacy turns saved
    /// before v5 of the chat-history schema.
    public var createdAt: Date?
    /// Wall-clock when an assistant stream finished naturally. Nil on
    /// user / tool turns, and on assistant turns that were cancelled,
    /// errored, or predate v5.
    public var completedAt: Date?
    /// Tokens generated by the assistant for this turn. GPU-timed for
    /// MLX, UI-estimated for remote APIs. Nil when unknown.
    public var generationTokenCount: Int?
    /// Seconds from request start to first visible token, for latency
    /// reporting. Nil when unknown.
    public var timeToFirstToken: TimeInterval?
    /// OpenAI Responses reasoning item captured for an assistant turn (opaque
    /// `id` + encrypted blob). Re-emitted for chain continuity. Nil for every
    /// non-Responses turn.
    public var reasoningItemId: String?
    public var reasoningEncrypted: String?

    public init(
        id: UUID = UUID(),
        role: MessageRole,
        content: String,
        attachments: [Attachment] = [],
        toolCalls: [ToolCall]? = nil,
        toolCallId: String? = nil,
        toolResults: [String: String] = [:],
        toolCallDurations: [String: TimeInterval] = [:],
        thinkingDuration: TimeInterval? = nil,
        thinking: String = "",
        createdAt: Date? = nil,
        completedAt: Date? = nil,
        generationTokenCount: Int? = nil,
        timeToFirstToken: TimeInterval? = nil,
        reasoningItemId: String? = nil,
        reasoningEncrypted: String? = nil
    ) {
        self.id = id
        self.role = role
        self.content = content
        self.attachments = attachments
        self.toolCalls = toolCalls
        self.toolCallId = toolCallId
        self.toolResults = toolResults
        self.toolCallDurations = toolCallDurations
        self.thinkingDuration = thinkingDuration
        self.thinking = thinking
        self.createdAt = createdAt
        self.completedAt = completedAt
        self.generationTokenCount = generationTokenCount
        self.timeToFirstToken = timeToFirstToken
        self.reasoningItemId = reasoningItemId
        self.reasoningEncrypted = reasoningEncrypted
    }

    // Backward-compatible decoder: migrates old `attachedImages` into unified `attachments`
    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        role = try container.decode(MessageRole.self, forKey: .role)
        content = try container.decode(String.self, forKey: .content)
        toolCalls = try container.decodeIfPresent([ToolCall].self, forKey: .toolCalls)
        toolCallId = try container.decodeIfPresent(String.self, forKey: .toolCallId)
        toolResults = try container.decodeIfPresent([String: String].self, forKey: .toolResults) ?? [:]
        toolCallDurations =
            try container.decodeIfPresent([String: TimeInterval].self, forKey: .toolCallDurations) ?? [:]
        thinkingDuration = try container.decodeIfPresent(TimeInterval.self, forKey: .thinkingDuration)
        thinking = try container.decodeIfPresent(String.self, forKey: .thinking) ?? ""
        createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt)
        completedAt = try container.decodeIfPresent(Date.self, forKey: .completedAt)
        generationTokenCount = try container.decodeIfPresent(Int.self, forKey: .generationTokenCount)
        timeToFirstToken = try container.decodeIfPresent(TimeInterval.self, forKey: .timeToFirstToken)
        reasoningItemId = try container.decodeIfPresent(String.self, forKey: .reasoningItemId)
        reasoningEncrypted = try container.decodeIfPresent(String.self, forKey: .reasoningEncrypted)

        if let unified = try container.decodeIfPresent([Attachment].self, forKey: .attachments) {
            attachments = unified
        } else {
            let legacyImages = try container.decodeIfPresent([Data].self, forKey: .attachedImages) ?? []
            attachments = legacyImages.map { .image($0) }
        }
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(role, forKey: .role)
        try container.encode(content, forKey: .content)
        try container.encode(attachments, forKey: .attachments)
        try container.encodeIfPresent(toolCalls, forKey: .toolCalls)
        try container.encodeIfPresent(toolCallId, forKey: .toolCallId)
        try container.encode(toolResults, forKey: .toolResults)
        if !toolCallDurations.isEmpty {
            try container.encode(toolCallDurations, forKey: .toolCallDurations)
        }
        try container.encodeIfPresent(thinkingDuration, forKey: .thinkingDuration)
        try container.encode(thinking, forKey: .thinking)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(generationTokenCount, forKey: .generationTokenCount)
        try container.encodeIfPresent(timeToFirstToken, forKey: .timeToFirstToken)
        try container.encodeIfPresent(reasoningItemId, forKey: .reasoningItemId)
        try container.encodeIfPresent(reasoningEncrypted, forKey: .reasoningEncrypted)
    }

    private enum CodingKeys: String, CodingKey {
        case id, role, content, attachments
        case attachedImages  // legacy key for reading old sessions
        case toolCalls, toolCallId, toolResults, toolCallDurations, thinking
        case thinkingDuration
        case createdAt, completedAt, generationTokenCount, timeToFirstToken
        case reasoningItemId, reasoningEncrypted
    }
}

// MARK: - Conversion Extensions

extension ChatTurnData {
    /// Convert from a ChatTurn instance
    @MainActor
    init(from turn: ChatTurn) {
        self.id = turn.id
        self.role = turn.role
        self.content = turn.content
        self.attachments = turn.attachments
        self.toolCalls = turn.toolCalls
        self.toolCallId = turn.toolCallId
        self.toolResults = turn.toolResults
        self.toolCallDurations = turn.toolCallDurations
        self.thinkingDuration = turn.thinkingDuration
        self.thinking = turn.thinking
        self.createdAt = turn.createdAt
        self.completedAt = turn.completedAt
        self.generationTokenCount = turn.generationTokenCount
        self.timeToFirstToken = turn.timeToFirstToken
        self.reasoningItemId = turn.reasoningItemId
        self.reasoningEncrypted = turn.reasoningEncrypted
    }
}

extension ChatTurn {
    /// Create a ChatTurn from persisted data (preserves original UUID for stable block IDs)
    convenience init(from data: ChatTurnData) {
        self.init(
            role: data.role,
            content: data.content,
            attachments: data.attachments,
            id: data.id,
            createdAt: data.createdAt ?? Date()
        )
        self.toolCalls = data.toolCalls
        self.toolCallId = data.toolCallId
        self.toolResults = data.toolResults
        self.toolCallDurations = data.toolCallDurations
        self.thinkingDuration = data.thinkingDuration
        self.thinking = data.thinking
        self.completedAt = data.completedAt
        self.generationTokenCount = data.generationTokenCount
        self.timeToFirstToken = data.timeToFirstToken
        self.reasoningItemId = data.reasoningItemId
        self.reasoningEncrypted = data.reasoningEncrypted
    }
}
