//
//  TestHelpers.swift
//  OsaurusStatsPackTests
//

import Foundation
import OsaurusCore

@testable import OsaurusStatsPack

enum TestHelpers {
    static func write(_ content: String, filename: String, in directory: URL? = nil) throws -> URL {
        let root = directory ?? FileManager.default.temporaryDirectory
        let url = root.appendingPathComponent("\(UUID().uuidString)-\(filename)")
        try content.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    static func writeSQLiteFixture(
        extension pathExtension: String = "sqlite",
        in directory: URL? = nil
    ) throws -> URL {
        let root = directory ?? FileManager.default.temporaryDirectory
        let url =
            root
            .appendingPathComponent("\(UUID().uuidString)-stats.\(pathExtension)")
        let data = Data(base64Encoded: sqliteFixtureBase64, options: .ignoreUnknownCharacters)!
        try data.write(to: url, options: .atomic)
        return url
    }

    static func collectRecords(from adapter: any FormatAdapter) async throws -> [Record] {
        var continuation: AsyncStream<Record>.Continuation?
        let stream = AsyncStream<Record> { continuation = $0 }
        let task = Task {
            try await adapter.streamRecords(into: continuation!)
        }

        var records: [Record] = []
        for await record in stream {
            records.append(record)
        }
        try await task.value
        return records
    }

    private static let sqliteFixtureBase64 = """
        U1FMaXRlIGZvcm1hdCAzAAIAAQEMQCAgAAAABQAAAAMAAAAAAAAAAAAAAAMAAAAEAAAAAAAAAAAAAAABAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFAC6N+A0AAAACAVIAAYcBUgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzAgYXFxcBR3RhYmxlbm90ZXNub3Rl
        cwNDUkVBVEUgVEFCTEUgbm90ZXMoYm9keSBURVhUKWsBBxcZGQGBMXRhYmxlcGVvcGxlcGVvcGxlAkNSRUFURSBUQUJMRSBw
        ZW9wbGUoaWQgSU5URUdFUiBQUklNQVJZIEtFWSwgbmFtZSBURVhULCBzY29yZSBSRUFMLCBhY3RpdmUgSU5URUdFUikAAAAA
        AAAAAAAAAAANAAAAAgHOAAHiAc4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAASAgUAFwcIR3JhY2VAN0AAAAAAABABBQATBwlBZGFAKQAA
        AAAAAAAAAAAAAAAAAAAAAA0AAAABAesAAesAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
        AAAABwECF2hlbGxvAAAAAAAAAAAAAAAA
        """
}
