//
//  PrivacyLocalizationTests.swift
//  osaurus / PrivacyFilter Tests
//
//  Regression guard for the original bug where most `privacy.*` keys
//  in `Localizable.xcstrings` shipped without an `en` value — every
//  string in the review sheet rendered as its key. This test parses
//  the catalog directly and asserts that every privacy key has a
//  non-empty English value.
//

import Foundation
import Testing

@testable import OsaurusCore

@Suite("Privacy localization completeness")
struct PrivacyLocalizationTests {

    private struct Catalog: Decodable {
        let strings: [String: Entry]

        struct Entry: Decodable {
            let localizations: [String: Localization]?
        }

        /// One language slot under `localizations`. May carry either a
        /// flat `stringUnit` (most strings) or a `variations.plural`
        /// dictionary (count-driven plural forms like
        /// `privacy.error.scrubLeaked.phone %lld`). Either is fine —
        /// at least one English value must exist.
        struct Localization: Decodable {
            let stringUnit: StringUnit?
            let variations: Variations?
        }

        struct Variations: Decodable {
            let plural: [String: PluralUnit]?
        }

        struct PluralUnit: Decodable {
            let stringUnit: StringUnit?
        }

        struct StringUnit: Decodable {
            let state: String
            let value: String
        }
    }

    @Test func everyPrivacyKey_hasNonEmptyEnglishValue() throws {
        // The catalog lives in the OsaurusCore bundle. Bundle.module
        // is generated by SwiftPM for the package's resources.
        guard
            let url = Bundle.module.url(
                forResource: "Localizable",
                withExtension: "xcstrings"
            )
        else {
            Issue.record("Localizable.xcstrings not bundled with OsaurusCore module")
            return
        }
        let data = try Data(contentsOf: url)
        let catalog = try JSONDecoder().decode(Catalog.self, from: data)

        // Every privacy.* key must have an English value. We don't
        // assert on translation state because translators can mark
        // strings as `new` during a localization pass — we just need
        // an English baseline to exist for runtime fallback.
        let privacyKeys = catalog.strings.keys.filter { $0.hasPrefix("privacy.") }
        #expect(!privacyKeys.isEmpty, "No privacy.* keys found in catalog — file may have been renamed")

        for key in privacyKeys.sorted() {
            guard let entry = catalog.strings[key] else { continue }
            guard let localizations = entry.localizations else {
                Issue.record("\(key): missing `localizations` block — runtime renders the key itself")
                continue
            }
            guard let en = localizations["en"] else {
                Issue.record("\(key): missing English (`en`) localization")
                continue
            }

            // Plural-variant entries (e.g. `privacy.error.scrubLeaked.phone %lld`)
            // store their text under `variations.plural.<one|other|…>.stringUnit`
            // instead of a top-level `stringUnit`. Treat either path
            // as valid — what we're guarding against is the original
            // bug where the value was missing entirely.
            let pluralValues =
                en.variations?.plural?.values
                .compactMap { $0.stringUnit?.value } ?? []
            if let unit = en.stringUnit {
                #expect(!unit.value.isEmpty, "\(key): English value is empty")
                #expect(
                    !unit.value.hasPrefix(key),
                    "\(key): English value (\(unit.value)) looks like a key echo"
                )
            } else if !pluralValues.isEmpty {
                for value in pluralValues {
                    #expect(!value.isEmpty, "\(key): plural variant has empty English value")
                    #expect(
                        !value.hasPrefix(key),
                        "\(key): plural variant value (\(value)) looks like a key echo"
                    )
                }
            } else {
                Issue.record("\(key): English localization has neither `stringUnit` nor `variations.plural`")
                continue
            }
        }
    }
}
