//
//  MemoryModels.swift
//  osaurus
//
//  Data types for the v2 memory system.
//
//  Three persistent layers, plus a transcript fallback:
//
//    1. Identity   — single row of stable user facts (auto-derived + explicit overrides)
//    2. PinnedFact — promoted, salience-scored facts with decay and use tracking
//    3. Episode    — per-session digest (summary, topics, decisions, entities, salience)
//    -. Transcript — raw turns, kept only for fallback retrieval
//
//  Per-turn extraction and the 7-type MemoryEntry enum from the v1 system are gone.
//  Distillation runs once per session, not per turn.
//

import Foundation

// MARK: - Layer 1: Identity

/// Stable user identity. Single row, regenerated lazily from explicit
/// overrides plus the most-salient pinned facts. The auto-derived `content`
/// is regenerated by the consolidator; `overrides` are user-authored and
/// always take precedence in context assembly.
public struct Identity: Codable, Sendable {
    /// Auto-derived narrative summary of who the user is. May be empty
    /// before the first consolidation pass runs.
    public var content: String
    /// Explicit user-authored facts that always appear in context. Listed
    /// before the auto-derived content during assembly.
    public var overrides: [String]
    /// Approximate token count of `content` (overrides are tiny so we don't
    /// budget them separately).
    public var tokenCount: Int
    /// Bumped each time the auto-derived `content` is regenerated.
    public var version: Int
    /// Model used for the most recent regeneration (or "user" when manually edited).
    public var model: String
    /// ISO8601 timestamp of the most recent regeneration.
    public var generatedAt: String

    public init(
        content: String = "",
        overrides: [String] = [],
        tokenCount: Int = 0,
        version: Int = 0,
        model: String = "",
        generatedAt: String = ""
    ) {
        self.content = content
        self.overrides = overrides
        self.tokenCount = tokenCount
        self.version = version
        self.model = model
        self.generatedAt = generatedAt
    }
}

// MARK: - Layer 2: Pinned Facts

/// A salience-scored fact promoted from one or more episodes. Replaces the
/// v1 `MemoryEntry` 7-type taxonomy with a single, ranked pool.
public struct PinnedFact: Codable, Sendable, Identifiable {
    public var id: String
    public var agentId: String
    public var content: String
    /// Relevance/importance score in [0, 1]. Decayed by the consolidator
    /// (`score *= exp(-Δdays / halfLife)`) and incremented when the fact
    /// is referenced by a new episode or surfaced in context.
    public var salience: Double
    /// Number of episodes that reference this fact (used by the consolidator
    /// to decide whether to promote a candidate to the pinned pool).
    public var sourceCount: Int
    /// Optional source episode ID — the episode that first promoted this fact.
    public var sourceEpisodeId: Int?
    /// ISO8601 timestamp of the most recent retrieval / context surface.
    public var lastUsed: String
    /// Bumped each time the fact is included in an assembled context.
    public var useCount: Int
    /// `active` | `evicted`. Evicted rows are kept briefly for audit before
    /// the consolidator hard-deletes them.
    public var status: String
    /// ISO8601 timestamp of insertion.
    public var createdAt: String
    /// Optional comma-separated keyword tags (lightweight; not used for
    /// ranking, only for UI filtering).
    public var tagsCSV: String?

    public var tags: [String] {
        guard let tagsCSV, !tagsCSV.isEmpty else { return [] }
        return tagsCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public init(
        id: String = UUID().uuidString,
        agentId: String,
        content: String,
        salience: Double = 0.5,
        sourceCount: Int = 1,
        sourceEpisodeId: Int? = nil,
        lastUsed: String = "",
        useCount: Int = 0,
        status: String = "active",
        createdAt: String = "",
        tagsCSV: String? = nil
    ) {
        self.id = id
        self.agentId = agentId
        self.content = String(content.prefix(MemoryConfiguration.maxContentLength))
        self.salience = min(1.0, max(0.0, salience))
        self.sourceCount = max(0, sourceCount)
        self.sourceEpisodeId = sourceEpisodeId
        self.lastUsed = lastUsed
        self.useCount = max(0, useCount)
        self.status = status
        self.createdAt = createdAt
        self.tagsCSV = tagsCSV
    }
}

// MARK: - Layer 3: Episodes

/// A per-session digest. Replaces both the v1 `ConversationSummary` and the
/// per-turn `MemoryEntry` extraction. One episode is produced per session by
/// `MemoryService.distillSession`, and contains everything the planner needs
/// to surface "what did we talk about" without going to the raw transcript.
public struct Episode: Codable, Sendable, Identifiable {
    public var id: Int
    public var agentId: String
    public var conversationId: String
    /// One- to three-sentence narrative summary of the session.
    public var summary: String
    /// Comma-separated topics, in order of relevance.
    public var topicsCSV: String
    /// Comma-separated entity names mentioned (people, projects, tools, …).
    /// Used by the relevance gate for entity-name hits.
    public var entitiesCSV: String
    /// Bullet-style decision list (newline-separated). Empty when the
    /// session didn't decide anything.
    public var decisions: String
    /// Bullet-style action items (newline-separated).
    public var actionItems: String
    /// Salience score in [0, 1]; decayed by the consolidator and used by
    /// the planner when picking which episodes to surface.
    public var salience: Double
    public var tokenCount: Int
    public var model: String
    /// ISO8601 timestamp of when the conversation actually happened (the
    /// session date, not the distillation date).
    public var conversationAt: String
    public var status: String
    /// ISO8601 timestamp of when the episode was distilled.
    public var createdAt: String

    public var topics: [String] {
        topicsCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public var entities: [String] {
        entitiesCSV.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }
    }

    public init(
        id: Int = 0,
        agentId: String,
        conversationId: String,
        summary: String,
        topicsCSV: String = "",
        entitiesCSV: String = "",
        decisions: String = "",
        actionItems: String = "",
        salience: Double = 0.5,
        tokenCount: Int = 0,
        model: String = "",
        conversationAt: String,
        status: String = "active",
        createdAt: String = ""
    ) {
        self.id = id
        self.agentId = agentId
        self.conversationId = conversationId
        self.summary = String(summary.prefix(MemoryConfiguration.maxContentLength))
        self.topicsCSV = topicsCSV
        self.entitiesCSV = entitiesCSV
        self.decisions = decisions
        self.actionItems = actionItems
        self.salience = min(1.0, max(0.0, salience))
        self.tokenCount = max(0, tokenCount)
        self.model = model
        self.conversationAt = conversationAt
        self.status = status
        self.createdAt = createdAt
    }
}

// MARK: - Transcript (raw turns; fallback retrieval only)

/// A single conversation turn. Renamed from v1's `ConversationChunk`. Kept
/// for retrieval fallback — never injected into the default context block.
public struct TranscriptTurn: Codable, Sendable, Identifiable {
    public var id: Int
    public var conversationId: String
    public var chunkIndex: Int
    public var role: String
    public var content: String
    public var tokenCount: Int
    public var createdAt: String
    public var agentId: String
    public var conversationTitle: String?

    public init(
        id: Int = 0,
        conversationId: String,
        chunkIndex: Int,
        role: String,
        content: String,
        tokenCount: Int,
        createdAt: String = "",
        agentId: String = "",
        conversationTitle: String? = nil
    ) {
        self.id = id
        self.conversationId = conversationId
        self.chunkIndex = chunkIndex
        self.role = role
        self.content = content
        self.tokenCount = tokenCount
        self.createdAt = createdAt
        self.agentId = agentId
        self.conversationTitle = conversationTitle
    }
}

// MARK: - Background Processing

/// Buffered conversation turn awaiting end-of-session distillation. The
/// write path inserts these and never blocks; the distiller drains them.
public struct PendingSignal: Codable, Sendable {
    public var id: Int
    public var agentId: String
    public var conversationId: String
    public var userMessage: String
    public var assistantMessage: String?
    public var status: String
    public var createdAt: String

    public init(
        id: Int = 0,
        agentId: String,
        conversationId: String,
        userMessage: String,
        assistantMessage: String? = nil,
        status: String = "pending",
        createdAt: String = ""
    ) {
        self.id = id
        self.agentId = agentId
        self.conversationId = conversationId
        self.userMessage = userMessage
        self.assistantMessage = assistantMessage
        self.status = status
        self.createdAt = createdAt
    }
}

public struct ProcessingStats: Sendable {
    public var totalCalls: Int = 0
    public var avgDurationMs: Int = 0
    public var successCount: Int = 0
    public var errorCount: Int = 0
}
