//
//  SchemaDumper.swift
//  osaurus
//
//  Regenerates `~/.osaurus/agents/<id>/schema.sql` after every schema
//  mutation (spec §7.2). The agent itself reads schema via
//  `db.schema()`; this file is for the user, git, support, export.
//  Auto-sync is automatic because we call this from inside the bridge
//  on every schema-changing path.
//

import Foundation

public enum SchemaDumper {
    /// Render and write `schema.sql` for the given agent's database.
    /// Atomic write so a half-finished dump can never replace the
    /// previous one. Skips the schema dump on disk failures because
    /// `schema.sql` is purely advisory — the canonical source of
    /// truth is the SQLite file itself.
    public static func dump(
        _ schema: AgentDatabaseSchema,
        for agentId: UUID
    ) {
        let url = OsaurusPaths.agentSchemaSQLFile(for: agentId)
        OsaurusPaths.ensureExistsSilent(url.deletingLastPathComponent())
        let body = render(schema)
        try? body.write(to: url, atomically: true, encoding: .utf8)
    }

    /// Render the dump as a string (exposed for tests).
    public static func render(_ schema: AgentDatabaseSchema) -> String {
        var lines: [String] = []
        lines.append("-- Auto-generated by Osaurus from the agent's SQLite database.")
        lines.append("-- The DB file is canonical; this file is a human-readable mirror.")
        lines.append("-- Regenerated on every schema mutation; do not edit by hand.")
        lines.append("")

        for table in schema.tables {
            lines.append("-- \(table.name)")
            if !table.purpose.isEmpty {
                lines.append("-- purpose: \(table.purpose)")
            }
            lines.append("CREATE TABLE \(table.name) (")
            var colDefs: [String] = []
            for col in table.columns {
                var def = "    \(col.name) \(col.type)"
                if col.primaryKey { def += " PRIMARY KEY" }
                if !col.nullable && !col.primaryKey { def += " NOT NULL" }
                if let dflt = col.defaultValue { def += " DEFAULT \(dflt)" }
                colDefs.append(def)
            }
            lines.append(colDefs.joined(separator: ",\n"))
            lines.append(");")

            for idx in table.indexes {
                let unique = idx.unique ? "UNIQUE " : ""
                lines.append(
                    "CREATE \(unique)INDEX \(idx.name) ON \(table.name) (\(idx.columns.joined(separator: ", ")));"
                )
            }
            lines.append("")
        }

        if !schema.views.isEmpty {
            lines.append("-- Saved views (_views table)")
            for view in schema.views {
                lines.append("-- \(view.name) (\(view.renderHint), refresh: \(view.refresh))")
                lines.append("-- SQL: \(view.sql)")
                lines.append("")
            }
        }
        return lines.joined(separator: "\n")
    }
}
